server:
  port: 8080
#  address: 192.168.117.89

eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://locahost:8761
          predicates:
            - Path= /eureka/**

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/users/**, /api/roles/** , /api/playerRates/** , /api/login

        - id: stadiums-service
          uri: lb://stadiums-service
          predicates:
            - Path=  /api/pitches/** , /api/pitchRates/** , /api/villes/**

        - id: reservations-service
          uri: lb://reservations-service
          predicates:
            - Path=  /api/reservations/** , /api/payments/**

        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=  /api/notifications/** , /api/messages/**

        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=  /api/storage/**

        - id: rabbitMq
          uri: lb://rabbitMq
          predicates:
            - Path=  /api/queues/**
  application:
    name: gatWay


