server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://locahost:8761
          predicates:
            - Path=  /eureka/**

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=  /api/users/** , /api/roles/** , /api/playerRates/**

        - id: stadiums-service
          uri: lb://stadiums-service
          predicates:
            - Path=  /api/pitches/** , /api/pitchRates/**

        - id: reservations-service
          uri: lb://reservations-service
          predicates:
            - Path=  /api/reservations/** , /api/payments/**

        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=  /api/notifications/**


