spring:
  application:
    name: security-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://pitches-managment-security-service1.ch2e01owm84h.us-east-1.rds.amazonaws.com:3306/pitchesManagmentSecurityService
    username: admin
    password: 123456789
#    url: jdbc:mysql://localhost:3306/testtt
#    username: root
#    password:

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


