spring:
  application:
    name: reservation-service
  data:
    mongodb:
      uri: mongodb://mongoDbUser:123456789@pitchesmanagmentreservationsservice.cluster-ch2e01owm84h.us-east-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: pitchesManagmentReservationsService
      username: mongoDbUser
      password: 123456789



server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


