spring:
  application:
    name: rabbitMq
  rabbitmq:
    username: guest
    password: guest
    port: 5672


server:
  port: 8086


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  topicExchangeName : internal.exchange
  queueName : notification-queue
  routingkey: api.notification.*
